---

  - name: Common | Install prereqs
    tags: common
    apt: name={{item}} state=present update_cache=yes cache_valid_time=600
    with_items:
        - build-essential
        - apt-transport-https
        - software-properties-common
        - wget
        - unzip
        - curl
        - python-pycurl
        - git

